# Configuración del Microservicio Arca Cotizador
server:
  port: 8080
  
spring:
  application:
    name: arca-cotizador
  
  # Configuración de WebFlux
  webflux:
    base-path: /api/v1

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Configuración de Logging
logging:
  level:
    com.arka.cotizador: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración específica del negocio
arca:
  cotizador:
    dias-validez: 30
    tasa-impuesto: 0.19
    margen-comercial: 0.20
    moneda-default: COP

# Configuración de URLs de microservicios externos
microservices:
    # ✅ MODIFICADO: URL del microservicio de cotización
    arca-cotizador:
        url: http://localhost:8080/api/v1/cotizaciones
    # ✅ MODIFICADO: URL del microservicio de gestión de solicitudes
    gestor-solicitudes:
        url: http://localhost:8081/api/v1/solicitudes
    arka:
        url: http://localhost:8083/api/v1/arka

    # ✅ AGREGADO: Configuración de reintentos
    retries:
        max-attempts: 3
        backoff-delay: 2000

    timeout:
        connection: 5000
        read: 10000

