# Configuración para el entorno de desarrollo
server:
  port: 8081

spring:
  profiles:
    active: dev

# Configuración de desarrollo
logging:
  level:
    com.arka.cotizador: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

# Configuración específica de desarrollo
arca:
  cotizador:
    debug-mode: true
    mock-providers: true
