# Configuración para el entorno de desarrollo
server:
  port: 8080

spring:
  profiles:
    active: dev

# Configuración de desarrollo
logging:
  level:
    com.arka.cotizador: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

# Configuración específica de desarrollo
arca:
  cotizador:
    debug-mode: true
    mock-providers: true

# Configuración de URLs de microservicios externos
microservices:
  # ✅ MODIFICADO: URL del microservicio de cotización
  arca-cotizador:
    url: http://proyecto-cotizador:8080/api/v1/cotizaciones
  # ✅ MODIFICADO: URL del microservicio de gestión de solicitudes
  gestor-solicitudes:
    url: http://proyecto-gestor-solicitudes:8081/api/v1/solicitudes
  arka:
    url: http://proyecto-arca:8083

  # ✅ AGREGADO: Configuración de reintentos
  retries:
    max-attempts: 3
    backoff-delay: 2000

  timeout:
    connection: 5000
    read: 10000